#Site settings
title: jose luis vega
email: vegaguinaga@gmail.com
description: "autodidacta"


#Build settings
markdown: kramdown
permalink: pretty

port: 8000

include: ['_includes/work']


sass:
  sass_dir: assets/css
  style: :nested
