#Site settings
title: jose vega
email: vegaguinaga@gmail.com
description: "Thinker // Developer //blogger"


#Build settings
markdown: kramdown
permalink: pretty

port: 8000

include: ['_includes/work']


sass:
  sass_dir: assets/css
  style: :nested
